sudo: required
os: linux
cache: false
language: bash
services:
- docker
jobs:
  include:
  - stage: test
    script:
    - docker build --target test-stage --tag salade2chats/devstroke:test --file docker/Dockerfile
      .
    - docker run --rm salade2chats/devstroke:test yarn run test:ci
  - stage: build
    if: tag IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build --target prod-stage --tag salade2chats/devstroke:$TRAVIS_TAG --file
      docker/Dockerfile .
    - docker tag salade2chats/devstroke:$TRAVIS_TAG salade2chats/devstroke:latest
    - docker push salade2chats/devstroke:$TRAVIS_TAG salade2chats/devstroke:latest
  - stage: deploy
    if: tas IS present
    provider: script
    skip_cleanup: true
    script:
      - ssh -ti /tmp/deploy_key devstroke@devstroke.io $TRAVIS_TAG
before_install:
- openssl aes-256-cbc -K $encrypted_e2cce3309739_key -iv $encrypted_e2cce3309739_iv
  -in travis/deploy_key.enc -out /tmp/deploy_key -d
- chmod 600 /tmp/deploy_key
