sudo: required
os: linux
cache: false
language: bash
services:
- docker
jobs:
  include:
  - stage: test
    script:
    - docker build --target test-stage --pull -t devstroke/www:test -f docker/Dockerfile .
    - docker run --rm devstroke/www:test yarn run test:ci
  - stage: build
    if: tag IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build --target prod-stage -t devstroke/www:$TRAVIS_TAG -f docker/Dockerfile .
    - docker tag devstroke/www:$TRAVIS_TAG devstroke/www:latest
    - docker push devstroke/www:$TRAVIS_TAG
    - docker push devstroke/www:latest
    - ssh -ti /tmp/deploy_key devstroke@devstroke.io devstroke-www $TRAVIS_TAG
before_install:
- openssl aes-256-cbc -K $encrypted_035c09b0931c_key -iv $encrypted_035c09b0931c_iv
  -in travis/deploy_key.enc -out /tmp/deploy_key -d
- chmod 600 /tmp/deploy_key
addons:
  ssh_known_hosts:
  - devstroke.io
