FROM node:10-alpine AS build-stage

ARG ANGULAR_VERSION=v7.0.0-rc.2

# add Angular CLI and config
RUN yarn global add @angular/cli@${ANGULAR_VERSION} \
  && ng config --global cli.packageManager yarn

WORKDIR /app

COPY package*.json yarn.lock /app/

RUN yarn install

COPY ./ /app/

RUN yarn run build --prod

FROM nginx:1.15-alpine

COPY --from=build-stage /app/dist/ /usr/share/nginx/html

COPY docker/dependencies/devstroke.conf /etc/nginx/conf.d/default.conf
